export const GET_CHARACTERS_AND_STASHTABS = 'GET_CHARACTERS_AND_STASHTABS';
export const IS_LOADING_CHARACTER = "IS_LOADING_CHARACTER";
export const IS_LOADING_CHARACTER_DONE = "IS_LOADING_CHARACTER_DONE";
export const IS_LOADING_STASH_ITEMS = "IS_LOADING_STASH_ITEMS";
export const IS_LOADING_STASH_ITEMS_DONE = "IS_LOADING_STASH_ITEMS_DONE";
export const GET_CHARACTER_ITEMS = 'GET_CHARACTER_ITEMS';
export const GET_STASHTAB_ITEMS = "GET_STASHTAB_ITEMS";